import Button from "../../../components/Button"
import image from '../../../assets/img/UNA-image.png'
import { useLocation, useNavigate } from "react-router"

const DeviceInstruction = () => {
	const location = useLocation()
	const navigate = useNavigate()

	const handleDismiss = () => {
		navigate(-1)
	}
	const handleConfirm = () => {
		navigate(location.pathname, { state: 'scenarioChoice' })
	}

	return (
		<div className="tw-flex tw-flex-col tw-gap-9">
			<h1 className="tw-text-[32px] tw-font-bold tw-text-center">Instructions for Use</h1>
			<div className="tw-flex tw-gap-9">
				<div className="tw-flex-1 tw-relative tw-pr-[35%]">
					<img src={image} alt="UNA device" className='tw-absolute tw-w-full tw-h-full tw-top-0 tw-left-0 tw-object-cover' />
				</div>
				<div className="tw-grow tw-flex-shrink-0 tw-basis-1/2 tw-flex tw-justify-center tw-flex-col tw-gap-9 tw-text-[26px]">
					<p>The imPulse&#8482; UNA collects inaudible vibrations and audible sounds generated by the body </p>
					<p>A map of these inaudible and audible sounds is captured and stored</p>
				</div>
			</div>
			<div className="tw-flex tw-gap-4">
				<Button style="dismiss" text="back" className="tw-flex-1 tw-text-xl tw-font-semibold tw-py-6" onClick={handleDismiss} />
				<Button style="confirm" text="continue" className="tw-flex-1 tw-text-xl tw-font-semibold tw-py-6" onClick={handleConfirm} />
			</div>
		</div>
	)
}

export default DeviceInstruction